function DisclaimersPage() {
  return (
    <div className="w-full py-16 h-full flex-1">
      <div className="max-w-[640px] mx-auto py-16 px-4">
        <div className="text-dark-purple text-left flex flex-col gap-y-6">
          <div className="flex flex-col gap-y-4">
            <div className="text-4xl">Disclaimer of Lumina</div>
            <div className="text-base font-Trebuchet">
              The International Coaching Federation (“ICF”) and each of its
              affiliated organization websites, as well as ICF generated
              materials may contain information, references to or content
              supplied by third parties. Information contained on those
              website(s) or in any written materials or content generated by ICF
              or the affiliated organizations referring to any specific third
              party (including vendors, members or other third parties) or its
              product(s), service(s) or process(es) or procedure(s), by trade
              name, trademark, service or product provider name or otherwise,
              does not constitute or imply the Lumina, recommendation, or
              favoring by ICF or any of its affiliated organization’s or their
              respective officers, directors, employees, agents, volunteers or
              contractors of the referenced third party content, person(s),
              product(s), service(s) or process(es).
            </div>
            <div className="text-base font-Trebuchet">
              ICF and each of its affiliated organizations specifically disclaim
              any Lumina, approval or recommendation, either expressed or
              implied, of any product(s), written content or materials,
              service(s), process(es) or procedure(s) developed, promoted,
              rendered or used by any third party.
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default DisclaimersPage;
